New 1.4 version

diff --git a/mwan3/files/usr/sbin/mwan3 b/mwan3/files/usr/sbin/mwan3
--- a/mwan3/files/usr/sbin/mwan3
+++ b/mwan3/files/usr/sbin/mwan3
@@ -2,38 +2,189 @@
 
 . /lib/network/config.sh
 
-EXTRA_COMMANDS="mwan_apply mwan_unload"
+extra_help() {
+	cat <<EOF
 
-mwan_ifup()
+	ifup <iface>	Start service on interface
+	ifdown <iface>	Stop service on interface
+	interfaces	Show interfaces status
+	policies	Show policies status
+	rules		Show rules status
+	status		Show all status
+EOF
+}
+
+EXTRA_COMMANDS="ifdown ifup interfaces policies rules status"
+EXTRA_HELP="$(extra_help)"
+
+
+ifdown()
 {
-	local DEVICE
-	local ENABLED
+	if [ -z "$1" ]; then
+		echo "Error: Expecting interface. Usage: mwan3 ifdown <interface>" && exit 0
+	fi
+
+	if [ -n "$2" ]; then
+		echo "Error: Too many arguments. Usage: mwan3 ifdown <interface>" && exit 0
+	fi
+
+	local device
 	
-	config_get ENABLED "$1" enabled 0
-	DEVICE=$(uci get -p /var/state network.$1.ifname) &> /dev/null
+	device=$(uci get -p /var/state network.$1.ifname) &> /dev/null
 	
-	if [ -n "$DEVICE" ] ; then
-		[ "$ENABLED" = "1" ] && [ "$(ip -4 route list table main dev $DEVICE default)" ] && ACTION=ifup INTERFACE=$1 DEVICE=$DEVICE /sbin/hotplug-call iface
+	if [ -e /var/run/mwan3track-$1.pid ] ; then
+		kill $(cat /var/run/mwan3track-$1.pid)
+		rm /var/run/mwan3track-$1.pid
+	fi
+
+	if [ -n "$device" ] ; then
+		ACTION=ifdown INTERFACE=$1 DEVICE=$device /sbin/hotplug-call iface
 	fi
 }
 
-mwan_unload()
+ifup()
 {
-	local rule
-	local table
+	config_load mwan3
+
+	if [ -z "$1" ]; then
+		echo "Expecting interface. Usage: mwan3 ifup <interface>" && exit 0
+	fi
+
+	if [ -n "$2" ]; then
+		echo "Too many arguments. Usage: mwan3 ifup <interface>" && exit 0
+	fi
+
+	local device enabled
+	
+	config_get enabled "$1" enabled 0
+
+	[ "$enabled" = 1 ] || echo "Interface not configured or enabled"
+
+	device=$(uci get -p /var/state network.$1.ifname) &> /dev/null
+	
+	if [ -n "$device" ] ; then
+		[ "$enabled" -eq 1 ] && ACTION=ifup INTERFACE=$1 DEVICE=$device /sbin/hotplug-call iface
+	fi
+}
+
+interfaces()
+{
+	config_load mwan3
+
+	local device enabled iface_id
+
+	echo "Interface status:"
+	
+	check_status()
+	{
+		device=$(uci get -p /var/state network.$1.ifname) &> /dev/null
+		config_get enabled "$1" enabled 0
+		let iface_id++
+
+		if [ "$enabled" -eq 1 ]; then
+			if [ -n "$(ip rule | awk '$5 == ("'$device'")')" -a -n "$(iptables -S mwan3_iface_$1 -t mangle 2> /dev/null)" -a -n "$(ip -4 route list table $iface_id default dev $device)" ]; then
+				if [ -n "$(uci get -p /var/state mwan3.wan.track_ip)" ]; then
+					if [ -n "$(ps | grep mwan3track | grep -v grep | sed '/.*mwan3track \([^ ]*\) .*$/!d;s//\1/' | awk '$1 == ("'$1'")')" ]; then
+						echo "Interface $1 is online (tracking active)"
+					else
+						echo "Interface $1 is online (tracking down)"
+					fi
+				else
+					echo "Interface $1 is online (tracking disabled)"
+				fi
+			elif [ -n "$(ip rule | awk '$5 == ("'$device'")')" -o -n "$(iptables -S mwan3_iface_$1 -t mangle 2> /dev/null)" -o -n "$(ip -4 route list table $iface_id default dev $device)" ]; then
+				echo "Interface $1 error"
+			else
+				if [ -n "$(uci get -p /var/state mwan3.wan.track_ip)" ]; then
+					if [ -n "$(ps | grep mwan3track | grep -v grep | sed '/.*mwan3track \([^ ]*\) .*$/!d;s//\1/' | awk '$1 == ("'$1'")')" ]; then
+						echo "Interface $1 is offline (tracking active)"
+					else
+						echo "Interface $1 is offline"
+					fi
+				fi
+			fi
+		else
+			echo "Interface $1 is disabled"
+		fi
+	}
+	config_foreach check_status interface
+	echo -e
+}
+
+policies()
+{
+	local percent policy share total_weight weight iface
+
+	for policy in $(iptables -S -t mangle | awk '{print $2}' | grep mwan3_policy_ | sort -u); do
+		echo "Policy $policy:" | sed 's/mwan3_policy_//g'
+
+		for iface in $(iptables -S $policy -t mangle | cut -s -d'"' -f2 | awk '{print $1}'); do
+			[ -n "$total_weight" ] || total_weight=$(iptables -S $policy -t mangle | grep "$iface " | cut -s -d'"' -f2 | awk '{print $3}')
+		done
+
+		for iface in $(iptables -S $policy -t mangle | cut -s -d'"' -f2 | awk '{print $1}'); do
+			weight=$(iptables -S $policy -t mangle | grep "$iface " | cut -s -d'"' -f2 | awk '{print $2}')
+			percent=$((($weight*100)/$total_weight))
+			echo " $iface ($percent%)"
+		done
+
+		[ -n "$iface" ] || echo " $(iptables -S $policy -t mangle | sed '/.*--comment \([^ ]*\) .*$/!d;s//\1/;q')"
+		
+		unset iface
+		unset total_weight
+
+		echo -e
+	done
+}
+rules()
+{
+	if [ -n "$(iptables -L mwan3_connected -t mangle 2> /dev/null)" ]; then
+		echo "Local connected networks:"
+		echo "destination policy hits" | awk '{ printf "%-19s%-19s%-9s%s\n",$1,$2,$3}'
+		echo "------------------------------------------------"
+		iptables -L mwan3_connected -t mangle -n -v 2> /dev/null | tail -n+3 | sed 's/mark.*//' | sed 's/mwan3_policy_//g' | awk '{printf "%-19s%-19s%-9s%s\n",$9,"default",$1}'
+		echo -e
+	fi
+
+	if [ -n "$(iptables -L mwan3_rules -t mangle 2> /dev/null)" ]; then
+		echo "Active rules:"
+		echo "source destination proto src-port dest-port policy hits" | awk '{ printf "%-19s%-19s%-7s%-14s%-14s%-18s%-9s%s\n",$1,$2,$3,$4,$5,$6,$7}'
+		echo "-----------------------------------------------------------------------------------------------------"
+		iptables -L mwan3_rules -t mangle -n -v 2> /dev/null | tail -n+3 | sed 's/mark.*//' | sed 's/mwan3_policy_//g' | awk '{ printf "%-19s%-19s%-7s%-14s%-14s%-18s%-9s%s\n",$8,$9,$4,$12,$15,$3,$1}'
+		echo -e
+	fi
+}
+
+status()
+{
+	interfaces
+	policies
+	rules
+}
+
+start()
+{
+	config_load mwan3
+	config_foreach ifup interface
+}
+
+stop()
+{
+	local route rule table
 
 	killall mwan3track &> /dev/null
 	rm /var/run/mwan3track-* &> /dev/null
 
-	for rule in $(ip -4 rule list | egrep '^10[0-9]{2}\:' | cut -d ':' -f 1); do
-		ip -4 rule del pref $rule &> /dev/null
-		ip -4 route flush table $rule &> /dev/null
+	for route in $(ip route list table all | sed 's/.*table \([^ ]*\) .*/\1/' |  awk '{print $1}' | awk '{for(i=1;i<=NF;i++) if($i+0>0) if($i+0<255) {print;break}}'); do
+		ip -4 route flush table $route &> /dev/null
 	done
 
-	iptables -D PREROUTING -t mangle -j mwan3_pre &> /dev/null
-	iptables -D INPUT -t mangle -j mwan3_post &> /dev/null
-	iptables -D OUTPUT -t mangle -j mwan3_pre &> /dev/null
-	iptables -D POSTROUTING -t mangle -j mwan3_post &> /dev/null
+	for rule in $(ip -4 rule list | egrep '^[1-2][0-9]{3}\:' | cut -d ':' -f 1); do
+		ip -4 rule del pref $rule &> /dev/null
+	done
+
+	iptables -D PREROUTING -t mangle -j mwan3_hook &> /dev/null
+	iptables -D OUTPUT -t mangle -j mwan3_hook &> /dev/null
 
 	for table in $(iptables -S -t mangle | awk '{print $2}' | grep mwan3 | sort -u); do
 		iptables -F $table -t mangle &> /dev/null
@@ -42,12 +193,9 @@ mwan_unload()
 	for table in $(iptables -S -t mangle | awk '{print $2}' | grep mwan3 | sort -u); do
 		iptables -X $table -t mangle &> /dev/null
 	done
-
 }
 
-mwan_apply()
-{
-	config_load mwan3
-	config_foreach mwan_ifup interface
-
+restart() {
+	stop
+	start
 }
